name: Bump version workflow

on:
  push:
    branches:
    - main

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    env:
      version_part: "${{contains(github.event.head_commit.message, 'FEAT') && 'minor' || 'patch'}}"
    steps:
    - name: debug/help
      run: echo $version_part
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: true
    - name: bump2version
      run: |
        pip install --no-cache-dir bump2version
        git config --global user.name "Git Action"
        git config --global user.email "git.action@users.noreply.github.com"
        ~/.local/bin/bumpversion --list $version_part
        git push
        git push --tags
