name: Bump version workflow

on:
  push:
    branches:
    - main

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    env:
      version_part: "${{contains(github.event.head_commit.message, 'FEAT') && 'minor' || 'patch'}}"
    steps:
    - name: debug/help
      run: echo $version_part
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: FragileTech/bump-version
      uses: FragileTech/bump-version@main
      with:
        commit_name: Your Company Bot
        commit_email: bot@your-company.com
        login: your-bot-login
        token: "${{ secrets.GITHUB_TOKEN }}"
