name: Bump version workflow

on:
  push:
    branches:
    - main

jobs:
  bump-version:
    name: Bump package version
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-20.04
    env:
      commit_subject: "${{ github.event.head_commit.message }}"
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: true
    - name: bump2version
      run: |
        set -x
        version_part="None"
        case $commit_subject in
          *fix:*   ) version_part=patch;;
          *feat:* ) version_part=minor;;
          *BREAKING_CHANGE:* ) version_part=major;;
          * ) exit 0;;
        esac
        echo Version Part: $version_part
        pip install --no-cache-dir bump2version
        git config --global user.name "Git Action"
        git config --global user.email "git.action@users.noreply.github.com"
        ~/.local/bin/bumpversion --list $version_part
        git push
        git push --tags
